config:
  password-min-lenght: 5
  password-max-lenght: 16

messages:
  no-permission: "§cYou don't have permission to do that!"
  reload-success: "§aYou reload the configuration file in §2%s §ams"

  register-completed: "§aYou have successfully registered!"
  already-registred: "§cYour account is already registered!\nType §l/login <password>§c to authenticate.."
  not-registered: "§cYou must be registered to do this!"
  success-unregistered: "§aYou have successfully unregistered!"
  player-never-join: "§cThe player never joined the server!"
  success-unlogin: "§aYou have successfully logged out."
  success-kick: "\n §aᴋɪᴄᴋ\n §f%player%§7 kicked §f%target%§7 dal server."

  success-login: "§aYou have successfully logged in!"
  already-authenticated: "§cYou are already authenticated!"
  not-authenticated: "§cYou must be logged in to do this.!"
  event-not-authenticated: "§cYou are not logged in, type /login <password>"
  password-uncorrect: "§cThe password you entered is incorrect!"
  player-never-authenticated: "§cThe player never authenticated!"

  password-unsecure: "§cThe password is not secure enough!"
  short-password: "§cThe password is too short!"
  long-password: "§cThe password is too long!"
  password-not-match: "§cThe password doesn't match!"
  same-password: "§cThe new password is identical to the current one!"
  success-changepassword: "§aYou have successfully changed your password.."

  usage-register: "§cUse /register <password> <password>"
  usage-login: "§cUse /login <password>"
  usage-unregister: "§cUse /unregister <password>"
  usage-unlogin: "§cUse /unlogin"
  usage-changepassword: "§cUse /changepassword <password> <nuovapassword>"
  usage-adminauth: "§cIncorrect command, Use /adminauth for information"
  usage-adminauth-checkip: "§cUse /adminauth checkip <player>"
  usage-adminauth-register: "§cUse /adminauth register <player> <password>"
  usage-adminauth-unregister: "§cUse /adminauth unregister <player>"
  usage-adminauth-changepassword: "§cUse /adminauth changepassword <player> <password>"
  usage-adminauth-kick: "§cUse /adminauth kick <player> <reason>"
  usage-adminauth-dupeip: "§cUse /adminauth dupeip [<player> | <ip>]"

  # permissions #
  # /unlogin -> ryzeauth.command.unlogin #
  # /unregister -> ryzeauth.command.unregister #
  # /changepassword -> ryzeauth.command.changepassword #
  # /adminauth -> ryzeauth.command.adminauth #
  # /adminauth dupeip -> ryzeauth.command.adminauth.dupeip #
  # /adminauth checkip -> ryzeauth.command.adminauth.checkip #
  # /adminauth reload -> ryzeauth.command.adminnauth.reload #
  # /adminauth kick -> ryzeauth.command.adminauth.kick #
  # /adminauth unregister -> ryzeauth.command.adminauth.unregister #
  # /adminauth changepassword -> ryzeauth.command.adminauth.changepassword #
  # /adminauth register -> ryzeauth.command.adminauth.register #
  # tabcomplete -> ryzeauth.command.tabcomplete #